code --install-extensions aaron-bond.better-comments
code --install-extensions antiantisepticeye.vscode-color-picker
code --install-extensions bierner.markdown-preview-github-styles
code --install-extensions bmewburn.vscode-intelephense-client
code --install-extensions bradlc.vscode-tailwindcss
code --install-extensions devsense.composer-php-vscode
code --install-extensions devsense.phptools-vscode
code --install-extensions devsense.profiler-php-vscode
code --install-extensions github.copilot
code --install-extensions github.copilot-chat
code --install-extensions github.github-vscode-theme
code --install-extensions gruntfuggly.todo-tree
code --install-extensions jpotterm.simple-vim
code --install-extensions mechatroner.rainbow-csv
code --install-extensions ms-python.debugpy
code --install-extensions ms-python.python
code --install-extensions ms-python.vscode-pylance
code --install-extensions ryuta46.multi-command
code --install-extensions visualstudioexptteam.intellicode-api-usage-examples
code --install-extensions visualstudioexptteam.vscodeintellicode
code --install-extensions vscodevim.vim
code --install-extensions wordpresstoolbox.wordpress-toolbox
